language: python

sudo: required

env:
  global:
    - DEPENDS="numpy"

python:
  - "2.7"
  - "3.4"
  - "3.5"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install gfortran-4.9
  - pip install $DEPENDS

install:
  - python setup.py install

script:
    - python stripack/__init__.py

notifications:
  email: false
