language: python

sudo: false

env:
  global:
    - DEPENDS="numpy"

python:
  - "2.7"
  - "3.4"
  - "3.5"

before_install:
  - pip install $DEPENDS

install:
  - python setup.py install

script:
    - python stripack/__init__.py

notifications:
  email: false
